# Generated by Django 3.2 on 2021-05-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_locationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Prenom',
        ),
    ]
